# Generated by Django 6.0.2 on 2026-07-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='flag_scope',
            field=models.CharField(choices=[('required', 'Flag required'), ('optional', 'Flag optional'), ('not_applicable', 'Flag not applicable')], default='required', help_text='Whether this service is offered within a flag context.', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='inactive', max_length=20)),
                ('accepts_new_requests', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_offerings', to='catalog.flag')),
            ],
            options={
                'ordering': ['service_type__name', 'flag__name', 'display_name', 'id'],
            },
        ),
    ]
