# Generated by Django 6.0.2 on 2026-07-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicetype_flag_scope_tenantserviceoffering'),
        ('organizations', '0003_tenantflagrelationship'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantserviceoffering',
            name='flag_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='organizations.tenantflagrelationship'),
        ),
        migrations.AddField(
            model_name='tenantserviceoffering',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_offerings', to='catalog.servicetype'),
        ),
        migrations.AddField(
            model_name='tenantserviceoffering',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantserviceoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('flag__isnull', True), ('flag_relationship__isnull', True)), fields=('tenant', 'service_type'), name='unique_unflagged_offering_per_tenant_service'),
        ),
        migrations.AddConstraint(
            model_name='tenantserviceoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('flag_relationship__isnull', False)), fields=('tenant', 'service_type', 'flag_relationship'), name='unique_offering_per_tenant_service_relationship'),
        ),
    ]
