# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('imo_number', models.CharField(help_text="Uniqueness is enforced PER TENANT (see Meta.constraints), not globally. REVIEW NOTE: IMO numbers are globally unique in the real world, but this platform is multi-tenant B2B SaaS — the same physical vessel can legitimately be a client of two different, unrelated maritime consultancies (e.g. switching agents, or using two agents for different flag jurisdictions). A global unique constraint would let Tenant A's vessel record block Tenant B from ever registering the same ship — a hard outage for a paying customer. Cross-tenant duplicate detection (useful for platform analytics) belongs in a reporting query, not a blocking DB constraint.", max_length=20)),
                ('vessel_type', models.CharField(blank=True, max_length=100)),
                ('current_flag', models.ForeignKey(blank=True, help_text="The vessel's flag today. A ServiceRequest carries its own Flag independently — e.g. a Change-of-Flag request targets a DIFFERENT flag than current_flag.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='catalog.flag')),
                ('customer', models.ForeignKey(help_text='The owning/operating customer.', on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'imo_number'), name='unique_imo_per_tenant')],
            },
        ),
    ]
