# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveIntegerField(default=1, help_text='How many documents of this type are required (e.g. passport copies for each crew member could be >1).')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_count', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False, help_text='DERIVED cache — see recompute_checklist_item(). Do not set directly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_items', to='catalog.documenttype')),
            ],
            options={
                'ordering': ['document_type__name'],
            },
        ),
    ]
