# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checklists', '0001_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='catalog.documenttype'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='catalog.flag'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='catalog.servicetype'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('service_request', 'document_type'), name='unique_checklist_item_per_request_and_doctype'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('service_type', 'flag', 'document_type'), name='unique_checklist_rule_per_service_flag_doctype'),
        ),
    ]
