# Generated by Django 6.0.2 on 2026-07-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicetype_flag_scope_tenantserviceoffering'),
        ('checklists', '0002_initial'),
        ('workflow', '0002_alter_workflowsteptemplate_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='code',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='operation_template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='workflow.operationtemplateversion'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='catalog.flag'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='catalog.servicetype'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_template_version__isnull', False)), fields=('operation_template_version', 'code'), name='unique_checklist_code_per_operation_version'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_template_version__isnull', False)), fields=('operation_template_version', 'document_type'), name='unique_checklist_doctype_per_operation_version'),
        ),
    ]
