# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestorganization',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestorganization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestorganization',
            constraint=models.UniqueConstraint(fields=('service_request', 'organization', 'role'), name='unique_org_role_per_service_request'),
        ),
    ]
