# Generated by Django 6.0.2 on 2026-07-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicetype_flag_scope_tenantserviceoffering'),
        ('organizations', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFlagRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('direct', 'Direct'), ('authorized_representative', 'Authorized representative'), ('correspondent', 'Correspondent'), ('partner', 'Partner'), ('referral', 'Referral'), ('other', 'Other')], max_length=35)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='inactive', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_relationships', to='catalog.flag')),
                ('partner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_relationships', to='organizations.organization')),
                ('registry_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registry_relationships', to='organizations.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['flag__name', 'relationship_type', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('partner_organization__isnull', True), ('registry_organization__isnull', True)), fields=('tenant', 'flag', 'relationship_type'), name='unique_direct_flag_relationship'), models.UniqueConstraint(condition=models.Q(('partner_organization__isnull', True), ('registry_organization__isnull', False)), fields=('tenant', 'flag', 'relationship_type', 'registry_organization'), name='unique_registry_flag_relationship'), models.UniqueConstraint(condition=models.Q(('partner_organization__isnull', False), ('registry_organization__isnull', True)), fields=('tenant', 'flag', 'relationship_type', 'partner_organization'), name='unique_partner_flag_relationship'), models.UniqueConstraint(condition=models.Q(('partner_organization__isnull', False), ('registry_organization__isnull', False)), fields=('tenant', 'flag', 'relationship_type', 'registry_organization', 'partner_organization'), name='unique_network_flag_relationship')],
            },
        ),
    ]
