# Generated by Django 6.0.2 on 2026-07-14 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('module_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deprecated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_capability_assignments', to='authorization.capability')),
            ],
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_default', models.BooleanField(default=False, help_text='True for roles created by provision_default_roles(). These can still be edited by tenant admins — the flag is informational, not a write-lock.')),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='roles', through='authorization.RoleCapability', to='authorization.capability')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.AddField(
            model_name='rolecapability',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='authorization.tenantrole'),
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='authorization.tenantrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tenantrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rolecapability',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='unique_capability_per_role'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role_assignment'),
        ),
    ]
