# Generated by Django 6.0.2 on 2026-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_message_id', models.CharField(help_text="The mail provider's Message-ID header — used to prevent re-ingesting the same email twice.", max_length=255, unique=True)),
                ('from_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField()),
                ('raw_body_storage_key', models.CharField(help_text='Pointer into the same S3-compatible storage documents use — the raw email body/EML is stored as a blob, not in the DB.', max_length=500)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched to ServiceRequest'), ('processed', 'Attachments Extracted'), ('ignored', 'Ignored (not case-relevant)')], default='unmatched', max_length=20)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
