# Generated by Django 6.0.2 on 2026-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('user', 'Internal User'), ('customer', 'Customer'), ('system', 'System')], max_length=20)),
                ('verb', models.CharField(help_text="e.g. 'document.uploaded', 'document.classified', 'checklist_item.completed', 'service_request.status_changed'", max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
