# Generated by Django 6.0.2 on 2026-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting_documents', 'Collecting Documents'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('waiting_external', 'Waiting External'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('reference_code', models.CharField(help_text='Human-facing case reference, e.g. LM-2026-0417.', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
