# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('tenants', '0001_initial'),
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='catalog.flag'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='catalog.servicetype'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='vessels.vessel'),
        ),
        migrations.AddField(
            model_name='servicerequestsequence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_sequences', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['tenant', 'status'], name='service_req_tenant__4f1ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['vessel'], name='service_req_vessel__915520_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestsequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'year'), name='unique_sequence_per_tenant_year'),
        ),
    ]
