# Generated by Django 6.0.2 on 2026-07-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicetype_flag_scope_tenantserviceoffering'),
        ('service_requests', '0002_initial'),
        ('workflow', '0002_alter_workflowsteptemplate_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='operation_template_version',
            field=models.ForeignKey(blank=True, help_text='Immutable published process recipe used for instantiation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='workflow.operationtemplateversion'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_offering',
            field=models.ForeignKey(blank=True, help_text='Tenant service catalog entry used to open this operation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='catalog.tenantserviceoffering'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='catalog.flag'),
        ),
    ]
