# Generated by Django 6.0.2 on 2026-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('document.uploaded', 'document.uploaded'), ('document.classified', 'document.classified'), ('document.superseded', 'document.superseded'), ('checklist_item.completion_changed', 'checklist_item.completion_changed'), ('service_request.created', 'service_request.created'), ('service_request.status_changed', 'service_request.status_changed'), ('workflow_step.status_changed', 'workflow_step.status_changed'), ('service_request_organization.attached', 'service_request_organization.attached')], help_text="WHEN: the domain event this rule listens for. Restricted to events the rule engine is actually wired to (see events.types.RULE_TRIGGERABLE_EVENT_TYPES) — a typo'd or unsupported event name is rejected at save time, not discovered later as a rule that silently never fires.", max_length=100)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='IF: a list of {"field": ..., "operator": "eq"|"neq"|"in", "value": ...} objects. ALL must match (implicit AND, no OR/nesting — see rules/conditions.py for the exact contract and the full list of supported `field` names per event_type). An empty list means the rule fires on every occurrence of event_type for this tenant.')),
                ('action_type', models.CharField(choices=[('activate_workflow_step', 'Activate Workflow Step'), ('change_service_request_state', 'Change ServiceRequest State'), ('assign_organization', 'Assign Organization'), ('create_activity_log_entry', 'Create Activity Log Entry')], max_length=50)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='THEN: parameters for action_type — e.g. {"step_code": "bunker"} for activate_workflow_step. See rules/actions.py for the exact schema each action_type expects.')),
                ('priority', models.IntegerField(default=0, help_text="Lower runs first when multiple rules match the same event. Purely an ordering hint — rules should not depend on each other's side effects within the same evaluation pass.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggering_event_type', models.CharField(max_length=100)),
                ('succeeded', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
