# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ruleexecutionlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='rules.rule'),
        ),
        migrations.AddField(
            model_name='ruleexecutionlog',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_execution_logs', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='ruleexecutionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['tenant', 'event_type', 'is_active'], name='rules_rule_tenant__da4281_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecutionlog',
            index=models.Index(fields=['service_request', '-created_at'], name='rules_rulee_service_509e01_idx'),
        ),
    ]
