# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('unclassified', 'Unclassified'), ('classified', 'Classified'), ('validated', 'Validated')], default='unclassified', max_length=20)),
                ('uploaded_by_type', models.CharField(choices=[('customer', 'Customer'), ('internal', 'Internal Staff'), ('system', 'System (e.g. email ingestion)')], max_length=20)),
                ('classification_confidence', models.FloatField(blank=True, help_text='Confidence score for predicted_document_type. Meaningless once document_type is confirmed.', null=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='checklists.checklistitem')),
                ('document_type', models.ForeignKey(blank=True, help_text='CONFIRMED type. Set only via documents.services.classify_document().', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.documenttype')),
                ('predicted_document_type', models.ForeignKey(blank=True, help_text="Phase 2: an AI classifier's suggestion, prior to human/system confirmation. Never read by checklist recompute logic — only `document_type` (confirmed) counts toward completion.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_documents', to='catalog.documenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
