# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('emails', '0002_initial'),
        ('service_requests', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_email',
            field=models.ForeignKey(blank=True, help_text='Phase 2: set when this Document was auto-extracted from an email attachment by the ingestion pipeline. Null for portal uploads and internal-staff uploads. Added now so the ingestion feature is additive, not a migration on a hot table later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_documents', to='emails.emailmessage'),
        ),
        migrations.AddField(
            model_name='document',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Points to the older version this document corrects/replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_set', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
    ]
