# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('service_requests', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, help_text='Set only when uploaded_by_type=internal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadlink',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_link', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='uploadlink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['service_request', 'status'], name='documents_d_service_f4d5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['checklist_item'], name='documents_d_checkli_cdb749_idx'),
        ),
    ]
