# Generated by Django 6.0.2 on 2026-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('is_external', models.BooleanField(default=False, help_text="True if this step's completion depends on an external organization's response (lawyer, flag authority, P&I club).")),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Steps that must be COMPLETED before this step becomes eligible to start.', related_name='dependents', to='workflow.workflowsteptemplate')),
                ('flag', models.ForeignKey(blank=True, help_text='Null = applies to this ServiceType regardless of flag.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_templates', to='catalog.flag')),
                ('responsible_organization_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_templates', to='catalog.organizationtype')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_templates', to='catalog.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked'), ('waiting_external', 'Waiting External'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_steps', to='organizations.organization')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='service_requests.servicerequest')),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowsteptemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workflowsteptemplate',
            constraint=models.UniqueConstraint(fields=('service_type', 'flag', 'code'), name='unique_step_code_per_service_flag'),
        ),
        migrations.AddConstraint(
            model_name='workflowstepinstance',
            constraint=models.UniqueConstraint(fields=('service_request', 'step_template'), name='unique_step_instance_per_request'),
        ),
    ]
