# Generated by Django 6.0.2 on 2026-07-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicetype_flag_scope_tenantserviceoffering'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowsteptemplate',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_templates', to='catalog.servicetype'),
        ),
        migrations.CreateModel(
            name='OperationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_templates', to='catalog.tenantserviceoffering')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operation_template_versions', to=settings.AUTH_USER_MODEL)),
                ('operation_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='workflow.operationtemplate')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_operation_template_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['operation_template', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='operation_template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_templates', to='workflow.operationtemplateversion'),
        ),
        migrations.AddConstraint(
            model_name='workflowsteptemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_template_version__isnull', False)), fields=('operation_template_version', 'code'), name='unique_step_code_per_operation_version'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplate',
            constraint=models.UniqueConstraint(fields=('service_offering', 'code'), name='unique_operation_template_code_per_offering'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('service_offering',), name='one_active_default_template_per_offering'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateversion',
            constraint=models.UniqueConstraint(fields=('operation_template', 'version_number'), name='unique_operation_template_version_number'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('operation_template',), name='one_published_version_per_operation_template'),
        ),
    ]
